### ISSUE TITLE
index.html does not work on chrome

### ISSUE THREAD

**Issue by jesseeichar** [mtkopone/scct#1]
Chrome does not consider 2 files in the same directory to be the same site so attempting to load the packages.html and summary.html files fails.  If you look at the scala docs they use iframes for this.  

It works fine on safari and firefox though so for now I am using those browsers.  

As an intermediate step you might want to add a check for the chrome browser and recommend using a different browser.

**Comment by mtkopone** [comment]
Bummer. Looks like chrome + ajax + localhost don't play together at all. Will try to find a workaround later.

**Comment by mtkopone** [comment]
Added a warning when trying to use Chrome. Also, I don't predict that Chrome will change their behaviour on this anytime soon.

If someone needs to use Chrome, I recommend something like http://copiousfreetime.rubyforge.org/heel/

Like so: 
    gem install heel
    cd $project/target/scala_2.8.0/coverage-report
    heel
