### ISSUE TITLE
Report generation fails in multi-module maven projects

### ISSUE THREAD

**Issue by aharin** [mtkopone/scct#10]
Scct cannot find source files when running as a part of a multi-module maven build. 

When maven does the compilation, the current working directory is project root. However when tests are run the current working directory is module root. As a result source files cannot be found during report generation.

The location of source files stored in coverage.dat is relative to the current working directory. This also causes problems if maven build is invoked from another directory e.g. mvn -f somefolder/pom.xml. Ideally location should be relative to the module root. I am not sure if there is a way to identify module root though. 

I have got a fix where during reporting phase relative paths are adjusted to be relative to the module root. However this would not fix an issue when the build is run from a different directory altogether.  Perhaps a better approach could be storing absolute paths in coverage.dat. Pull request to follow.

**Comment by mtkopone** [comment]
Heh, after quite a while, this should now work with the 0.2-SNAPSHOT version and onwards.
