### ISSUE TITLE
Support for sbt 0.10.x

### ISSUE THREAD

**Issue by lucastorri** [mtkopone/scct#13]
Any plans?

Thanks a lot

**Comment by mtkopone** [comment]
Hi, 

I did a bit of googling and ran into this: https://github.com/dvc94ch/sbt-scct

I haven't tried it myself. If you do, let me know if it works OK so then I can just relax instead of having to basically learn a new language for sbt 0.10.

**Comment by jestan** [comment]
It works, Thanks a lot :)

**Comment by mtkopone** [comment]
I'm closing this issue as it seems there are plugins for the more recent versions of sbt in the wild. 

I haven't tried them myself, so YMMV, but here's what I gather:

For sbt 0.11.0: https://github.com/quelgar/sbt-scct
For sbt 0.10.1: https://github.com/dvc94ch/sbt-scct
