### ISSUE TITLE
Support for Scala 2.9.1

### ISSUE THREAD

**Issue by inkytonik** [mtkopone/scct#15]
Do you plan to do a release for Scala 2.9.1?  I image in that there shouldn't be too much change from the 2.9.0-1 version, but who knows?

thanks,
Tony

**Comment by mtkopone** [comment]
Yeah, coming.

I'm having a look today, hopefully it'll be quick & easy.

**Comment by inkytonik** [comment]
Cool.  Thanks for looking into it.

**Comment by mtkopone** [comment]
That should do it.

Give it a go.

**Comment by inkytonik** [comment]
Thanks! Seems to be working for me once I told the sbt-scct plugin to use 2.9.1.
