### ISSUE TITLE
Classloader issue with Surefire

### ISSUE THREAD

**Issue by 0x6e6562** [mtkopone/scct#2]
When I turn coverage on for my Maven module, when the Surefire phase kicks off, all of the tests fail with this error:

java.lang.NoClassDefFoundError: Could not initialize class reaktor.scct.Coverage$

which occurs in the constructor of each test class. I've tried putting the reaktor.scct_2.8.0 dependency onto the compile time scope, but this doesn't seem to help.

Is this a known issue?

**Comment by mtkopone** [comment]
Hi. 

Are you using the profile like in the instructions? If so, the scct.jar should be in the classpath when running the tests. Also, note that the profile config requires that maven-scala-plugin is correctly configured for the project.

Please also note that after running "mvn -Pcoverage clean test", the compiled sources are now instrumented, therefore running stg like "mvn test" after that will cause the error you encountered. So a clean is required after that. This is something that I hope to fix soon, probably by compiling the instrumented sources to another subdirectory of target.

The whole maven support is pretty beta, and I expect there's gonna be a lot of maven-madness before it works nicely.

**Comment by mtkopone** [comment]
Closing this since it's been inactive for a couple of months. 

Feel free to reopen if there are still issued.
