### ISSUE TITLE
How to use with Build.scala?

### ISSUE THREAD

**Issue by diegovar** [mtkopone/scct#32]
I can't seem to figure out how the following line:

```
seq(ScctPlugin.instrumentSettings : _*)
```

Translates to a project that uses Build.scala instead of build.sbt. Do I have to import something?

Thanks

Diego

**Comment by mtkopone** [comment]
Firstly, your `project/build.sbt` needs to contain:

```
resolvers += Classpaths.typesafeResolver

resolvers += "scct-github-repository" at "http://mtkopone.github.com/scct/maven-repo"

addSbtPlugin("reaktor" % "sbt-scct" % "0.2-SNAPSHOT")
```

... for "loading" the plugin. Note the filename, it's in **project/**, not at the root.

Then...

For simple projects, you can mix and match build.sbt and Build.scala, so if you have a simple project your `build.sbt` can contain `seq(ScctPlugin.instrumentSettings : _*)`. And that should be enough.

If you have a more complex (maybe multiproject) setup, then your Build.scala defines the Project(s). In that case, adding the instrumentation settings to the each projects settings should work, like `project/MyBuild.scala`:

```
import sbt._
import sbt.Keys._

object MyBuild extends Build {
  lazy val myProject = Project("myProject", file("."), settings = Project.defaultSettings ++ ScctPlugin.instrumentSettings)
}
```

Hope this helps, feel free to close the issue if it's resolved.

**Comment by diegovar** [comment]
Excellent, that worked, thanks!
