### ISSUE TITLE
A report with 0% coverage is not created

### ISSUE THREAD

**Issue by asomov** [mtkopone/scct#36]
When the tests do not cover any code (if tests are just place holders), the report is not generated. The message is this:

scct: Timed out waiting for coverage report.

**Comment by mtkopone** [comment]
Yeah, It's a bit of a problem. Basically, if **nothing** calls scct, then the classes in charge of creating the report don't even get class-loaded.

Perhaps a better error-message would be enough?

**Comment by asomov** [comment]
Sorry for the delay.
Yes, I think a proper error message would solve the problem. This error only happens in the very beginning.

**Comment by asomov** [comment]
too old
