### ISSUE TITLE
Not able to resolve scct for Scala 2.9.2, 0.2-SNAPSHOT, in sbt 0.12.0

### ISSUE THREAD

**Issue by thricejamie** [mtkopone/scct#37]
Until recently, I was resolving scct without problems, but this has stopped working. I see that you recently removed Scala 2.9 build options, but not sure whether this would have propagated to the repo.

Using sbt 0.12.0

I have the following in my project/build.sbt:

```
resolvers += Classpaths.typesafeResolver

resolvers += "scct-github-repository" at "http://mtkopone.github.com/scct/maven-repo"

addSbtPlugin("reaktor" % "sbt-scct" % "0.2-SNAPSHOT")
```

Build ends up failing:

```
[info] Resolving reaktor#scct_2.9.2;0.2-SNAPSHOT ...
[warn]  module not found: reaktor#scct_2.9.2;0.2-SNAPSHOT
[warn] ==== local: tried
[warn]   /Users/jamie/.ivy2/local/reaktor/scct_2.9.2/0.2-SNAPSHOT/ivys/ivy.xml
[warn] ==== scct-repository: tried
[warn]   file:///Users/mtkopone/dev/scct-root/gh-pages/maven-repo/reaktor/scct_2.9.2/0.2-SNAPSHOT/scct_2.9.2-0.2-SNAPSHOT.pom
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/reaktor/scct_2.9.2/0.2-SNAPSHOT/scct_2.9.2-0.2-SNAPSHOT.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: reaktor#scct_2.9.2;0.2-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency: reaktor#scct_2.9.2;0.2-SNAPSHOT: not found
...
```

**Comment by mtkopone** [comment]
Sorry about that, my local development repository settings got into the published version. Gonna have to find a better way of isolating them.

Fixed binaries are now in place. Everything should work.

(2.9 build setting removal is only relevant to the 2.10 branch, which should therefore only affect 2.10 users)

Thanks for the heads up,

**Comment by thricejamie** [comment]
Thanks for the quick fix.

**Comment by Anjaiah** [comment]
Hi, I am also facing the same problem. How you have fixed this issue. I did not get mtkopone explanation
