### ISSUE TITLE
About versioning and/or tagging policy

### ISSUE THREAD

**Issue by kmizu** [mtkopone/scct#38]
Now I use scct 0.2-SNAPSHOT with Scala 2.9.1.  Of course, I understand it is snapshot version and
its risk.  Recently, you changed scalaVersion to "2.10.0.-RC3" in build.sbt.

Since Scala doesn't have binary compatibility between major version, if you publish scct without changing its version and with updating scalaVersion in build.sbt, it confuses and breaks my build  (probably, other users).  If you put tag before updating scalaVersion, it's not problematic.

Then, if you don't mind, please put tag (e.g. 0.2-M1) before updateing scalaVersion.  If tagging is painful for you, I woule like to contribute since I think scct is useful and now use it.

**Comment by mtkopone** [comment]
Hi, 

I'm trying to keep master as the bleeding edge of development, with old versions being branched out whenever necessary. The current master is therefore only for 2.10 and up, and it therefore won't build binaries for 2.9 and earlier.

There's a branch for the current 2.9.2 version, which has been taken from master before the first commits relating to 2.10 we're introduced. Any issues with 2.9 will therefore get fixed there.

Oops... What I just realized is that I forgot to push that branch to github, so it's only local at the moment. Sorry about that. Will push it as soon as I get to the machine.

**Comment by mtkopone** [comment]
The scala-2.9.2 branch is now in github.
