### ISSUE TITLE
Compile error with TestSetup and TestCleanup when using sbt 0.7.5

### ISSUE THREAD

**Issue by leothekim** [mtkopone/scct#4]
When using sbt 0.7.5 and starting up sbt, I get this:

[info] Recompiling plugin...
[info]    Source analysis: 1 new/modified, 0 indirectly invalidated, 0 removed.
[error] /Users/leo/Documents/workspace/foursquare.web/project/plugins/src_managed/sbt-scct-for-2.8-0.1-SNAPSHOT/reaktor/scct/ScctProject.scala:41: overloaded method value apply with alternatives ((java.lang.ClassLoader) => Option[String])ScctProject.this.TestSetup <and> (() => Option[String])ScctProject.this.TestSetup cannot be applied to (object None)
[error]     testOptions ++ Seq(TestSetup(setProps), TestCleanup(reportNow))
[error]                        ^
[error] /Users/leo/Documents/workspace/foursquare.web/project/plugins/src_managed/sbt-scct-for-2.8-0.1-SNAPSHOT/reaktor/scct/ScctProject.scala:41: overloaded method value apply with alternatives ((java.lang.ClassLoader) => Option[String])ScctProject.this.TestCleanup <and> (() => Option[String])ScctProject.this.TestCleanup cannot be applied to (object None)
[error]     testOptions ++ Seq(TestSetup(setProps), TestCleanup(reportNow))
[error]                                             ^
[error] two errors found
Compilation failed

There's a simple fix to get this working again. Will attach a patch.

**Comment by leothekim** [comment]
<pre><code>
diff --git a/sbt-scct/src/main/scala/reaktor/scct/ScctProject.scala b/sbt-scct/src/main/scala/reaktor/scct/ScctProject.scala
index 1623fc9..68ef0a6 100644
--- a/sbt-scct/src/main/scala/reaktor/scct/ScctProject.scala
+++ b/sbt-scct/src/main/scala/reaktor/scct/ScctProject.scala
@@ -38,7 +38,7 @@ trait ScctProject extends BasicScalaProject with MavenStyleScalaPaths {
   protected def instrumentedTestRunClassPath =
     testRuntimeScctPluginJar +++ instrumentedClassDir +++ (testClasspath --- mainCompilePath)
   protected def instrumentedTestOptions =
-    testOptions ++ Seq(TestSetup(setProps), TestCleanup(reportNow))
+    testOptions ++ Seq(TestSetup(() => setProps), TestCleanup(() => reportNow))
   protected def setProps() = {
     println("Setting props for "+name)
     System.setProperty("scct.report.hook", "system.property")
</code></pre>

**Comment by mtkopone** [comment]
Hi, 
Sorry for the late response, I've been on vacation and haven't had the time to look into sbt 0.7.5.

I'll have a look at integrating the patch during the next couple of days.

Thanks,

**Comment by mtkopone** [comment]
Thank you for the patch. 

It's included in the latest 0.1-SNAPSHOT release, so updating your scct-plugin should fix the issue.
