### ISSUE TITLE
Feature Request: Ability to run only certain tests

### ISSUE THREAD

**Issue by theon** [mtkopone/scct#48]
I have a mixture of ScalaTest unit tests and ScalaMeter performance benchmark tests in my project and I would like scct to only run the unit tests. 

Without using scct I can run `test-only com.github.theon.*` to run only the unit tests and `test-only benchmarks.*` to run the performance benchmark tests. With scct, I can only run `scct:test` to run both sets of tests. It would be great to be able to run something like `scct:test-only com.github.theon.*`.

**Comment by pjrt** [comment]
You can do this by running `sbt scct-test:test-only com.github.theon.*`

**Comment by theon** [comment]
Awesome, thanks Pedro. This should be added to the docs. I'll send a pull request.

**Comment by theon** [comment]
Closing this issue. Update to docs in pull request #58

**Comment by thetrav** [comment]
test-only in my case is executing all tests
