### ISSUE TITLE
Rebuild for SBT 0.13

### ISSUE THREAD

**Issue by stig** [mtkopone/scct#65]
Please make a new build available with SBT 0.13 support!

**Comment by ktoso** [comment]
+1

**Comment by 0xRoch** [comment]
+1

**Comment by nestorpersist** [comment]
+1

**Comment by folone** [comment]
+1

**Comment by 0xRoch** [comment]
I guess you will have to fork it / pull request because the project hasn't been active for a while

**Comment by 0xRoch** [comment]
https://github.com/SCCT/scct

**Comment by stig** [comment]
Closing issue to get it out of my /issues list, since this is unlikely to go anywhere now :-)
