### ISSUE TITLE
Exclude folders

### ISSUE THREAD

**Issue by 0xRoch** [mtkopone/scct#66]
I would like to know if there is a way I can exclude files/folders from SCCT coverage just like in JaCoCO : 
jacoco.excludes in jacoco.Config := Seq("views_", "Routes", "controllers_routes_", "controllers_Reverse_", "controllers_javascript_", "controller_ref*"),

**Comment by Johnlon** [comment]
See https://github.com/mtkopone/scct/pull/68
This is working for me.

**Comment by 0xRoch** [comment]
great thanks i'll give it a try did you host it on some mvn repo ?
