### ISSUE TITLE
Non zero (Summary 40 %) coverage for empty tests 

### ISSUE THREAD

**Issue by plokhotnyuk** [mtkopone/scct#9]
Any idea what is causing this? Or am I simply not using maven plug-ins correctly?

Source file src\main\scala\Sum.scala that contains:

<pre>
object Sum {
  def main(args: Array[String]) {
    try {
      val elems = args map Integer.parseInt
      println("The sum of my arguments is: " + elems.foldRight(0) (_ + _))
    } catch {
      case e: NumberFormatException => 
        println("Usage: scala Sum <n1> <n2> ... ")
    }
  }
}
</pre>

Test file src\test\scala\SumTest.scala with empty test:

<pre>
import org.junit.Test
import org.scalatest.FunSuite
import org.scalatest.matchers.ShouldMatchers
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class SumTest extends FunSuite with ShouldMatchers {
  test("Nothing") {
  }
}
</pre>

And the pom.xml file:

<pre>
&lt;project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd"&gt;
    &lt;modelVersion&gt;4.0.0&lt;/modelVersion&gt;
    &lt;groupId&gt;coverage&lt;/groupId&gt;
    &lt;artifactId&gt;coverage&lt;/artifactId&gt;
    &lt;version&gt;1.0-SNAPSHOT&lt;/version&gt;
    &lt;properties&gt;
        &lt;maven.compiler.source&gt;1.6&lt;/maven.compiler.source&gt;
        &lt;maven.compiler.target&gt;1.6&lt;/maven.compiler.target&gt;
        &lt;encoding&gt;UTF-8&lt;/encoding&gt;
        &lt;scala.version&gt;2.9.0-1&lt;/scala.version&gt;
    &lt;/properties&gt;
    &lt;repositories&gt;
        &lt;repository&gt;
            &lt;id&gt;scala-tools.org&lt;/id&gt;
            &lt;name&gt;Scala-Tools Maven2 Repository&lt;/name&gt;
            &lt;url&gt;http://scala-tools.org/repo-releases&lt;/url&gt;
        &lt;/repository&gt;
    &lt;/repositories&gt;
    &lt;pluginRepositories&gt;
        &lt;pluginRepository&gt;
            &lt;id&gt;scala-tools.org&lt;/id&gt;
            &lt;name&gt;Scala-Tools Maven2 Repository&lt;/name&gt;
            &lt;url&gt;http://scala-tools.org/repo-releases&lt;/url&gt;
        &lt;/pluginRepository&gt;
    &lt;/pluginRepositories&gt;
    &lt;dependencies&gt;
        &lt;dependency&gt;
            &lt;groupId&gt;org.scala-lang&lt;/groupId&gt;
            &lt;artifactId&gt;scala-library&lt;/artifactId&gt;
            &lt;version&gt;${scala.version}&lt;/version&gt;
        &lt;/dependency&gt;
        &lt;dependency&gt;
            &lt;groupId&gt;junit&lt;/groupId&gt;
            &lt;artifactId&gt;junit&lt;/artifactId&gt;
            &lt;version&gt;4.8.1&lt;/version&gt;
            &lt;scope&gt;test&lt;/scope&gt;
        &lt;/dependency&gt;
        &lt;dependency&gt;
            &lt;groupId&gt;org.scalatest&lt;/groupId&gt;
            &lt;artifactId&gt;scalatest_2.9.0&lt;/artifactId&gt;
            &lt;version&gt;1.6.1&lt;/version&gt;
            &lt;scope&gt;test&lt;/scope&gt;
        &lt;/dependency&gt;
    &lt;/dependencies&gt;
    &lt;build&gt;
        &lt;sourceDirectory&gt;src/main/scala&lt;/sourceDirectory&gt;
        &lt;testSourceDirectory&gt;src/test/scala&lt;/testSourceDirectory&gt;
        &lt;plugins&gt;
            &lt;plugin&gt;
                &lt;groupId&gt;org.scala-tools&lt;/groupId&gt;
                &lt;artifactId&gt;maven-scala-plugin&lt;/artifactId&gt;
                &lt;version&gt;2.15.2&lt;/version&gt;
                &lt;executions&gt;
                    &lt;execution&gt;
                        &lt;goals&gt;
                            &lt;goal&gt;compile&lt;/goal&gt;
                            &lt;goal&gt;testCompile&lt;/goal&gt;
                        &lt;/goals&gt;
                    &lt;/execution&gt;
                &lt;/executions&gt;
            &lt;/plugin&gt;
            &lt;plugin&gt;
                &lt;groupId&gt;org.apache.maven.plugins&lt;/groupId&gt;
                &lt;artifactId&gt;maven-surefire-plugin&lt;/artifactId&gt;
                &lt;version&gt;2.9&lt;/version&gt;
                &lt;configuration&gt;
                    &lt;useFile&gt;false&lt;/useFile&gt;
                    &lt;disableXmlReport&gt;true&lt;/disableXmlReport&gt;
                    &lt;includes&gt;
                        &lt;include&gt;**/*Test.*&lt;/include&gt;
                        &lt;include&gt;**/*Suite.*&lt;/include&gt;
                    &lt;/includes&gt;
                &lt;/configuration&gt;
            &lt;/plugin&gt;
        &lt;/plugins&gt;
    &lt;/build&gt;
    &lt;profiles&gt;
        &lt;profile&gt;
            &lt;id&gt;scct&lt;/id&gt;
            &lt;repositories&gt;
                &lt;repository&gt;
                    &lt;id&gt;scct repository&lt;/id&gt;
                    &lt;url&gt;http://mtkopone.github.com/scct/maven-repo&lt;/url&gt;
                &lt;/repository&gt;
            &lt;/repositories&gt;
            &lt;dependencies&gt;
                &lt;dependency&gt;
                    &lt;groupId&gt;reaktor&lt;/groupId&gt;
                    &lt;artifactId&gt;scct_${scala.version}&lt;/artifactId&gt;
                    &lt;version&gt;0.1-SNAPSHOT&lt;/version&gt;
                &lt;/dependency&gt;
            &lt;/dependencies&gt;
            &lt;build&gt;
                &lt;plugins&gt;
                    &lt;plugin&gt;
                        &lt;groupId&gt;org.scala-tools&lt;/groupId&gt;
                        &lt;artifactId&gt;maven-scala-plugin&lt;/artifactId&gt;
                        &lt;version&gt;2.14.2&lt;/version&gt;
                        &lt;inherited&gt;true&lt;/inherited&gt;
                        &lt;configuration&gt;
                            &lt;compilerPlugins&gt;
                                &lt;compilerPlugin&gt;
                                    &lt;groupId&gt;reaktor&lt;/groupId&gt;
                                    &lt;artifactId&gt;scct_${scala.version}&lt;/artifactId&gt;
                                    &lt;version&gt;0.1-SNAPSHOT&lt;/version&gt;
                                &lt;/compilerPlugin&gt;
                            &lt;/compilerPlugins&gt;
                        &lt;/configuration&gt;
                    &lt;/plugin&gt;
                    &lt;plugin&gt;
                        &lt;groupId&gt;org.apache.maven.plugins&lt;/groupId&gt;
                        &lt;artifactId&gt;maven-surefire-plugin&lt;/artifactId&gt;
                        &lt;version&gt;2.9&lt;/version&gt;
                        &lt;inherited&gt;true&lt;/inherited&gt;
                        &lt;configuration&gt;
                            &lt;systemPropertyVariables&gt;
                                &lt;scct.project.name&gt;${project.name}&lt;/scct.project.name&gt;
                                &lt;scct.coverage.file&gt;${project.build.outputDirectory}/coverage.data&lt;/scct.coverage.file&gt;
                                &lt;scct.report.dir&gt;${project.build.directory}/coverage-report&lt;/scct.report.dir&gt;
                                &lt;scct.source.dir&gt;${project.build.sourceDirectory}&lt;/scct.source.dir&gt;
                            &lt;/systemPropertyVariables&gt;
                        &lt;/configuration&gt;
                    &lt;/plugin&gt;
                &lt;/plugins&gt;
            &lt;/build&gt;
        &lt;/profile&gt;
    &lt;/profiles&gt;
&lt;/project&gt;
</pre>

**Comment by plokhotnyuk** [comment]
The following command was used to build the coverage report:

<pre>
mvn clean install -Pscct
</pre>

**Comment by mtkopone** [comment]
Hi,

For some reason, the scct compiler plugin is used for both compiling the main sources (as it should) and for compiling the test sources (which it shouldn't). 

This causes the test run to load the wrong coverage info, ie. that of the test sources.

I've forgotten most of the maven I know, but changing the scct-profile-specific maven-scala-plugin xml to the following seems to have helped:

```
<plugin>
  <groupId>org.scala-tools</groupId>
  <artifactId>maven-scala-plugin</artifactId>
  <executions>
    <execution>
      <id>scct-main-compile</id>
      <configuration>
          <compilerPlugins>
              <compilerPlugin>
                  <groupId>reaktor</groupId>
                  <artifactId>scct_${scala.version}</artifactId>
                  <version>0.1-SNAPSHOT</version>
              </compilerPlugin>
          </compilerPlugins>
      </configuration>
      <goals><goal>compile</goal></goals>
    </execution>
  </executions>
</plugin>
```

(The next dealie your going to run into is that since nothing is invoking the coverage-code during the test run, it's not going to create a report at all...)

**Comment by mtkopone** [comment]
Disregard the above. 

Instructions at http://mtkopone.github.com/scct/#usage-4-tabs-2 have been improved.
